DROP TABLE IF EXISTS event_compilations;
DROP TABLE IF EXISTS compilation;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(512) NOT NULL,
    email varchar(512) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(50) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uq_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS compilation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title varchar(50) NOT NULL,
    pinned boolean NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id),
    CONSTRAINT uq_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat float NOT NULL,
    lon float NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation varchar(2000) NOT NULL,
    category_id BIGINT REFERENCES category (id) NOT NULL ,
    confirmedRequests BIGINT,
    createdOn TIMESTAMP,
    description varchar(7000),
    eventDate TIMESTAMP NOT NULL,
    initiator_id BIGINT REFERENCES users (id) NOT NULL,
    location_id BIGINT REFERENCES location (id) NOT NULL,
    paid boolean NOT NULL,
    participantLimit integer,
    publishedOn TIMESTAMP,
    requestModeration boolean,
    state varchar(64),
    title varchar(120) NOT NULL,
    views BIGINT,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event_compilations (
    event_id BIGINT REFERENCES events (id) NOT NULL,
    compilation_id BIGINT REFERENCES compilation (id) NOT NULL
);